apiVersion: release-notes/v2
kind: bug-fix
area: installation

releaseNotes:
- |
  **Fixed** values in the Istio Gateway Helm charts for configuring annotations on the Service.  Can be used to configure load balancer in public clouds.
